USE DAOUDAOU;
CREATE TABLE USER(
	EMAIL VARCHAR(100),
	NAME VARCHAR(10),
    PASSWORD VARCHAR(20)
);
CREATE TABLE EVENT(
	EVENT_KEY INT,
    EMAIL VARCHAR(100),
    DATETIME DATETIME,
    TITLE VARCHAR(50),
    CONTENT VARCHAR(300)
);
CREATE TABLE ROUTINE(
	ROUTINE_KEY INT,
    EMAIL VARCHAR(100),
    DAY INT,
    TITLE VARCHAR(50),
    CONTENT VARCHAR(300)
);
INSERT INTO USER VALUES("ROOT", "ROOT", "ROOOT");